// Package controller implements the claim/wake/warm/GC loops on top of the
// Cursor fleet API and a backend.
package controller

import (
	"context"
	"errors"
	"fmt"
	"log/slog"
	"sync"
	"time"

	"go.opentelemetry.io/otel"
	"go.opentelemetry.io/otel/attribute"
	"go.opentelemetry.io/otel/codes"
	"go.opentelemetry.io/otel/trace"

	"github.com/ewhauser/cursor-controller/internal/backend"
	"github.com/ewhauser/cursor-controller/internal/cursorapi"
	"github.com/ewhauser/cursor-controller/internal/metrics"
)

// tracer is a no-op until telemetry.Setup installs a provider.
var tracer = otel.Tracer("github.com/ewhauser/cursor-controller/internal/controller")

// Span attribute keys.
const (
	attrRequestID = attribute.Key("cursor.request_id")
	attrWorkerID  = attribute.Key("cursor.worker_id")
	attrPool      = attribute.Key("cursor.pool")
	attrKind      = attribute.Key("cursor.spawn_kind")
	attrResult    = attribute.Key("cursor.result")
	attrReason    = attribute.Key("cursor.dispose_reason")
)

func spanResult(span trace.Span, result string, err error) {
	span.SetAttributes(attrResult.String(result))
	if err != nil {
		span.RecordError(err)
		span.SetStatus(codes.Error, result)
	}
}

// Config tunes the controller loops.
type Config struct {
	// Pools to watch. Empty watches every pool the key can see.
	Pools []string
	// Repository filter for repo-scoped service accounts (optional).
	Repository string
	// WorkerIDPrefix is used to mint ids and recognise our own workers.
	WorkerIDPrefix string
	// WarmIdle keeps this many idle workers connected per pool (0 = claim mode only).
	WarmIdle int
	// WarmInterval is the warm-idle reconcile period.
	WarmInterval time.Duration
	// ResyncInterval bounds how long one SSE stream is held before re-listing.
	ResyncInterval time.Duration
	// ReconnectDelay is the pause after a stream error before re-listing.
	ReconnectDelay time.Duration
	// WakeRetryInterval is the pause between transient backend wake failures.
	WakeRetryInterval time.Duration
	// GCInterval is the disposal reconcile period (0 disables GC).
	GCInterval time.Duration
	// DisposeAfter is the hard TTL: an offline worker idle this long is disposed
	// whatever its agent status is (0 disables).
	DisposeAfter time.Duration
	// DisposeArchivedAfter disposes offline workers whose agent is ARCHIVED (or
	// deleted) once idle this long. Only used when CheckAgent is true.
	DisposeArchivedAfter time.Duration
	// DisposeUnclaimedAfter disposes offline workers that never received a
	// request (warm workers that idled out) after this long (0 disables).
	DisposeUnclaimedAfter time.Duration
	// CheckAgent queries GET /v1/agents/{id} during GC.
	CheckAgent bool
	// ExitOnAuthError makes Run return on 401/403 so the process restarts
	// loudly instead of spinning.
	ExitOnAuthError bool
	// APIURL is passed to workers.
	APIURL string
}

func (c *Config) defaults() {
	if c.WorkerIDPrefix == "" {
		c.WorkerIDPrefix = "cc"
	}
	if c.WarmInterval <= 0 {
		c.WarmInterval = time.Minute
	}
	if c.ResyncInterval <= 0 {
		c.ResyncInterval = 4 * time.Minute
	}
	if c.ReconnectDelay <= 0 {
		c.ReconnectDelay = 5 * time.Second
	}
	if c.WakeRetryInterval <= 0 {
		c.WakeRetryInterval = 2 * time.Second
	}
	seen := make(map[string]struct{}, len(c.Pools))
	pools := make([]string, 0, len(c.Pools))
	for _, pool := range c.Pools {
		if _, ok := seen[pool]; ok {
			continue
		}
		seen[pool] = struct{}{}
		pools = append(pools, pool)
	}
	c.Pools = pools
}

// API is the subset of cursorapi.Client the controller needs (mockable).
type API interface {
	ListAllPendingRequests(ctx context.Context, opts cursorapi.ListOptions) ([]cursorapi.PendingRequest, string, error)
	StreamPendingRequests(ctx context.Context, opts cursorapi.StreamOptions, fn func(cursorapi.Event) error) error
	ClaimRequest(ctx context.Context, requestID, workerID string) (*cursorapi.Claim, error)
	ReleaseClaim(ctx context.Context, requestID string) (*cursorapi.Claim, error)
	GetPoolForRepository(ctx context.Context, name, repository string) (*cursorapi.Pool, error)
	ListAllWorkers(ctx context.Context, opts cursorapi.WorkerListOptions) ([]cursorapi.Worker, error)
	GetWorker(ctx context.Context, workerID string) (*cursorapi.Worker, error)
	GetAgent(ctx context.Context, agentID string) (*cursorapi.Agent, error)
}

// ErrAuth is returned by Run when the API rejects the key and ExitOnAuthError is set.
var ErrAuth = errors.New("cursor api rejected the api key")

// Controller runs the loops.
type Controller struct {
	cfg     Config
	api     API
	backend backend.Backend
	log     *slog.Logger
	m       *metrics.Metrics
	now     func() time.Time

	inflight sync.Map // request id or worker id -> struct{}
	// recentClaims suppresses resolving the id-only claimed event generated by
	// our own atomic claim; those workers already persist the request in Spawn.
	recentClaims sync.Map // request id -> *struct{}
	handlers     sync.WaitGroup
	fatal        chan error
	fatalOnce    sync.Once

	agentCheckDisabled bool
	agentCheckMu       sync.Mutex
}

// New creates a Controller.
func New(cfg Config, api API, be backend.Backend, log *slog.Logger, m *metrics.Metrics) *Controller {
	cfg.defaults()
	if log == nil {
		log = slog.Default()
	}
	if m == nil {
		m = metrics.New()
	}
	return &Controller{cfg: cfg, api: api, backend: be, log: log, m: m, now: time.Now, fatal: make(chan error, 1)}
}

// Run blocks until ctx is cancelled or a fatal error occurs.
func (c *Controller) Run(ctx context.Context) error {
	ctx, cancel := context.WithCancel(ctx)
	defer cancel()
	var wg sync.WaitGroup
	watchPool := ""
	if len(c.cfg.Pools) == 1 {
		watchPool = c.cfg.Pools[0]
	}
	wg.Add(1)
	go func() { defer wg.Done(); c.watchLoop(ctx, watchPool) }()
	for _, pool := range c.cfg.Pools {
		if c.cfg.WarmIdle > 0 && pool != "" {
			wg.Add(1)
			go func(pool string) { defer wg.Done(); c.warmLoop(ctx, pool) }(pool)
		}
	}
	if c.cfg.GCInterval > 0 {
		wg.Add(1)
		go func() { defer wg.Done(); c.gcLoop(ctx) }()
	}
	var err error
	select {
	case <-ctx.Done():
	case err = <-c.fatal:
		cancel()
	}
	wg.Wait()
	c.handlers.Wait()
	return err
}

func (c *Controller) abort(err error) {
	c.fatalOnce.Do(func() { c.fatal <- err })
}

// authCheck reports auth failures and, when configured, aborts the run.
func (c *Controller) authCheck(err error) {
	if err == nil || !cursorapi.IsAuthError(err) {
		return
	}
	c.log.Error("cursor api rejected the api key; pool workers need a team service-account key with agent scope", "err", err)
	if c.cfg.ExitOnAuthError {
		c.abort(fmt.Errorf("%w: %v", ErrAuth, err))
	}
}

// handlerTimeout bounds one claim/spawn or wake attempt.
const handlerTimeout = 5 * time.Minute

// runHandler runs fn on a context detached from shutdown cancellation so an
// in-flight spawn can finish (or release its claim) instead of being torn
// down half-way, while still bounding it with a timeout.
func runHandler(parent context.Context, fn func(ctx context.Context)) {
	hctx, cancel := context.WithTimeout(context.WithoutCancel(parent), handlerTimeout)
	defer cancel()
	fn(hctx)
}

func sleepCtx(ctx context.Context, d time.Duration) bool {
	if d <= 0 {
		return ctx.Err() == nil
	}
	t := time.NewTimer(d)
	defer t.Stop()
	select {
	case <-ctx.Done():
		return false
	case <-t.C:
		return true
	}
}

// ---------------------------------------------------------------------------
// watch loop: list -> handle -> stream -> repeat

func (c *Controller) watchLoop(ctx context.Context, pool string) {
	log := c.log.With("pool", poolLabel(pool))
	backoff := time.Second
	for ctx.Err() == nil {
		reqs, cursor, err := c.api.ListAllPendingRequests(ctx, cursorapi.ListOptions{Pool: pool, Repository: c.cfg.Repository, Limit: 100})
		if err != nil {
			if ctx.Err() != nil {
				return
			}
			c.m.ListRuns.WithLabelValues(poolLabel(pool), "error").Inc()
			log.Error("list pending requests", "err", err)
			c.authCheck(err)
			if !sleepCtx(ctx, backoff) {
				return
			}
			backoff = min(backoff*2, 30*time.Second)
			continue
		}
		backoff = time.Second
		c.m.ListRuns.WithLabelValues(poolLabel(pool), "ok").Inc()
		c.m.SetReady(true)
		log.Debug("listed pending requests", "count", len(reqs))
		for i := range reqs {
			r := &reqs[i]
			if pool == "" && len(c.cfg.Pools) > 0 && !c.servesPool(r.Pool()) {
				continue
			}
			runHandler(ctx, func(hctx context.Context) { c.handleRequest(hctx, r) })
		}
		if cursor == "" {
			log.Warn("list response had no streamCursor; polling instead")
			if !sleepCtx(ctx, c.cfg.ReconnectDelay) {
				return
			}
			continue
		}
		cause := c.watchStream(ctx, pool, cursor)
		if ctx.Err() != nil {
			return
		}
		c.m.StreamReconnects.WithLabelValues(poolLabel(pool), cause).Inc()
		if cause != "resync" && cause != "cursor_expired" {
			if !sleepCtx(ctx, c.cfg.ReconnectDelay) {
				return
			}
		}
	}
}

// watchStream holds the SSE stream for at most ResyncInterval and returns the
// reason it stopped: resync, cursor_expired, closed, or error.
func (c *Controller) watchStream(ctx context.Context, pool, cursor string) string {
	log := c.log.With("pool", poolLabel(pool))
	sctx, cancel := context.WithTimeout(ctx, c.cfg.ResyncInterval)
	defer cancel()
	log.Debug("opening pending-request stream")
	err := c.api.StreamPendingRequests(sctx, cursorapi.StreamOptions{Pool: pool, Repository: c.cfg.Repository, Cursor: cursor}, func(ev cursorapi.Event) error {
		c.handleEvent(ctx, pool, ev)
		return nil
	})
	switch {
	case err == nil:
		log.Info("stream closed by server; re-listing")
		return "closed"
	case errors.Is(sctx.Err(), context.DeadlineExceeded) && ctx.Err() == nil:
		log.Debug("resync interval elapsed; re-listing")
		return "resync"
	case errors.Is(err, cursorapi.ErrCursorExpired):
		log.Info("stream cursor expired; re-listing")
		return "cursor_expired"
	case ctx.Err() != nil:
		return "shutdown"
	default:
		log.Error("stream error; re-listing", "err", err)
		c.authCheck(err)
		return "error"
	}
}

func (c *Controller) handleEvent(ctx context.Context, pool string, ev cursorapi.Event) {
	log := c.log.With("pool", poolLabel(pool), "event", ev.Type)
	switch ev.Type {
	case cursorapi.EventCreated, cursorapi.EventClaimedOffline:
		r, err := cursorapi.DecodeRequest(ev.Data)
		if err != nil {
			log.Warn("undecodable event payload", "err", err, "data", truncate(ev.Data, 300))
			return
		}
		if ev.Type == cursorapi.EventClaimedOffline && r.ClaimedWorkerID == "" {
			log.Warn("claimed_offline event without claimedWorkerId", "request", r.ID)
			return
		}
		if pool == "" && len(c.cfg.Pools) > 0 && !c.servesPool(r.Pool()) {
			log.Debug("ignoring event for unconfigured pool", "request_pool", r.Pool())
			return
		}
		// Handle off the stream goroutine so a slow spawn (image pull, hook
		// script) never stalls event delivery. The in-flight guard dedupes.
		c.handlers.Add(1)
		go func() {
			defer c.handlers.Done()
			runHandler(ctx, func(hctx context.Context) { c.handleRequest(hctx, r) })
		}()
	case cursorapi.EventClaimed:
		e, err := cursorapi.DecodeClaimEvent(ev.Data)
		if err != nil {
			log.Warn("undecodable claimed payload", "err", err)
			return
		}
		if _, claimedHere := c.recentClaims.Load(e.ID); claimedHere {
			return
		}
		c.handlers.Add(1)
		go func() {
			defer c.handlers.Done()
			runHandler(ctx, func(hctx context.Context) {
				if e.WorkerID != "" {
					c.recordClaim(hctx, e.WorkerID, e.ID, log)
					return
				}
				c.resolveClaim(hctx, e.ID, log)
			})
		}()
	case cursorapi.EventExpired:
		log.Info("request expired", "data", truncate(ev.Data, 200))
	case cursorapi.EventHeartbeat, "":
	default:
		log.Debug("ignoring event")
	}
}

func (c *Controller) servesPool(pool string) bool {
	for _, configured := range c.cfg.Pools {
		if configured == pool {
			return true
		}
	}
	return len(c.cfg.Pools) == 0
}

func (c *Controller) recordClaim(ctx context.Context, workerID, requestID string, log *slog.Logger) bool {
	if !c.backend.Owns(workerID) {
		return false
	}
	if err := c.backend.RecordClaim(ctx, workerID, requestID); err != nil {
		log.Warn("record claim", "worker", workerID, "request", requestID, "err", err)
		return false
	}
	log.Info("request claimed by our worker", "worker", workerID, "request", requestID)
	return true
}

const (
	claimResolveTimeout  = 30 * time.Second
	claimResolveInterval = time.Second
)

// resolveClaim maps Cursor's id-only claimed event back to a warm worker using
// the connected-worker inventory and its activeBcId field.
func (c *Controller) resolveClaim(ctx context.Context, requestID string, log *slog.Logger) {
	ctx, cancel := context.WithTimeout(ctx, claimResolveTimeout)
	defer cancel()
	for {
		workers, err := c.api.ListAllWorkers(ctx, cursorapi.WorkerListOptions{Status: "all", Scope: "team_pool", Limit: 100})
		if err == nil {
			for _, worker := range workers {
				if worker.ActiveBcID == requestID && c.recordClaim(ctx, worker.WorkerID, requestID, log) {
					return
				}
			}
		} else {
			c.authCheck(err)
			log.Warn("resolve claimed worker", "request", requestID, "err", err)
		}
		if !sleepCtx(ctx, claimResolveInterval) {
			log.Warn("could not map claimed request to a connected worker", "request", requestID)
			return
		}
	}
}

// handleRequest routes one pending request: wake for offline claims we own,
// claim-then-spawn otherwise.
func (c *Controller) handleRequest(ctx context.Context, r *cursorapi.PendingRequest) {
	if r.IsOfflineClaim() {
		c.wake(ctx, r)
		return
	}
	c.claimAndSpawn(ctx, r)
}

func (c *Controller) claimAndSpawn(ctx context.Context, r *cursorapi.PendingRequest) {
	pool := r.Pool()
	log := c.log.With("request", r.ID, "pool", pool)
	if _, busy := c.inflight.LoadOrStore("req:"+r.ID, struct{}{}); busy {
		return
	}
	defer c.inflight.Delete("req:" + r.ID)

	workerID := backend.NewWorkerID(c.cfg.WorkerIDPrefix)
	claimToken := &struct{}{}
	c.recentClaims.Store(r.ID, claimToken)
	ctx, span := tracer.Start(ctx, "controller.claim_and_spawn",
		trace.WithAttributes(attrRequestID.String(r.ID), attrPool.String(pool), attrWorkerID.String(workerID), attrKind.String(string(backend.KindClaim))))
	defer span.End()
	if _, err := c.api.ClaimRequest(ctx, r.ID, workerID); err != nil {
		c.recentClaims.CompareAndDelete(r.ID, claimToken)
		switch {
		case errors.Is(err, cursorapi.ErrConflict):
			c.m.Claims.WithLabelValues(pool, "conflict").Inc()
			spanResult(span, "conflict", nil)
			log.Debug("request already claimed")
		case errors.Is(err, cursorapi.ErrNotFound):
			c.m.Claims.WithLabelValues(pool, "gone").Inc()
			spanResult(span, "gone", nil)
			log.Debug("request no longer pending")
		default:
			c.m.Claims.WithLabelValues(pool, "error").Inc()
			spanResult(span, "claim_error", err)
			log.Error("claim failed", "err", err)
			c.authCheck(err)
		}
		return
	}
	time.AfterFunc(claimResolveTimeout, func() { c.recentClaims.CompareAndDelete(r.ID, claimToken) })
	c.m.Claims.WithLabelValues(pool, "claimed").Inc()
	log = log.With("worker", workerID)
	log.Info("claimed request; spawning worker", "repo", r.RepoURL, "user", r.UserID)

	spec := backend.Spec{WorkerID: workerID, Pool: pool, Kind: backend.KindClaim, Request: r, APIURL: c.cfg.APIURL}
	if err := c.backend.Spawn(ctx, spec); err != nil {
		c.m.Spawns.WithLabelValues(pool, string(backend.KindClaim), "error").Inc()
		spanResult(span, "spawn_error", err)
		log.Error("spawn failed; releasing claim", "err", err)
		c.release(ctx, r.ID, "spawn_failed")
		return
	}
	c.m.Spawns.WithLabelValues(pool, string(backend.KindClaim), "ok").Inc()
	spanResult(span, "spawned", nil)
}

func (c *Controller) wake(ctx context.Context, r *cursorapi.PendingRequest) {
	pool := r.Pool()
	workerID := r.ClaimedWorkerID
	log := c.log.With("request", r.ID, "pool", pool, "worker", workerID)
	if !c.backend.Owns(workerID) {
		c.m.Wakes.WithLabelValues(pool, "foreign").Inc()
		log.Debug("offline claim belongs to a worker we did not mint; ignoring")
		return
	}
	if _, busy := c.inflight.LoadOrStore("wake:"+workerID, struct{}{}); busy {
		return
	}
	defer c.inflight.Delete("wake:" + workerID)

	ctx, span := tracer.Start(ctx, "controller.wake",
		trace.WithAttributes(attrRequestID.String(r.ID), attrPool.String(pool), attrWorkerID.String(workerID), attrKind.String(string(backend.KindWake)),
			attribute.Int64("cursor.wake_timeout_ms", r.WakeTimeoutMs)))
	defer span.End()
	log.Info("waking hibernated worker", "wake_timeout", r.WakeTimeout())
	spec := backend.Spec{WorkerID: workerID, Pool: pool, Kind: backend.KindWake, Request: r, WakeTimeout: r.WakeTimeout(), APIURL: c.cfg.APIURL}
	wakeCtx := ctx
	cancel := func() {}
	if spec.WakeTimeout > 0 {
		wakeCtx, cancel = context.WithTimeout(ctx, spec.WakeTimeout)
	}
	defer cancel()
	var err error
	for {
		err = c.backend.Wake(wakeCtx, spec)
		if err == nil || errors.Is(err, backend.ErrWorkspaceMissing) || errors.Is(err, backend.ErrUnknownWorker) || spec.WakeTimeout <= 0 || wakeCtx.Err() != nil {
			break
		}
		log.Warn("wake failed; retrying within Cursor wake window", "err", err, "retry_in", c.cfg.WakeRetryInterval)
		if !sleepCtx(wakeCtx, c.cfg.WakeRetryInterval) {
			break
		}
	}
	switch {
	case err == nil:
		c.m.Wakes.WithLabelValues(pool, "woken").Inc()
		c.m.Spawns.WithLabelValues(pool, string(backend.KindWake), "ok").Inc()
		spanResult(span, "woken", nil)
	case errors.Is(err, backend.ErrWorkspaceMissing), errors.Is(err, backend.ErrUnknownWorker):
		c.m.Wakes.WithLabelValues(pool, "missing").Inc()
		spanResult(span, "workspace_missing", nil)
		log.Warn("cannot wake worker; releasing claim so Cursor re-queues the request", "err", err)
		c.release(ctx, r.ID, "workspace_missing")
	default:
		c.m.Wakes.WithLabelValues(pool, "error").Inc()
		c.m.Spawns.WithLabelValues(pool, string(backend.KindWake), "error").Inc()
		spanResult(span, "wake_error", err)
		log.Error("wake failed before Cursor wake window elapsed", "err", err)
	}
}

func (c *Controller) release(ctx context.Context, requestID, reason string) {
	c.recentClaims.Delete(requestID)
	ctx, cancel := context.WithTimeout(context.WithoutCancel(ctx), 15*time.Second)
	defer cancel()
	ctx, span := tracer.Start(ctx, "controller.release", trace.WithAttributes(attrRequestID.String(requestID), attrReason.String(reason)))
	defer span.End()
	if _, err := c.api.ReleaseClaim(ctx, requestID); err != nil && !errors.Is(err, cursorapi.ErrNotFound) {
		spanResult(span, "release_failed", err)
		c.m.Releases.WithLabelValues(reason + "_failed").Inc()
		c.log.Error("release claim", "request", requestID, "reason", reason, "err", err)
		return
	}
	c.m.Releases.WithLabelValues(reason).Inc()
}

// ---------------------------------------------------------------------------
// warm-idle loop

func (c *Controller) warmLoop(ctx context.Context, pool string) {
	log := c.log.With("pool", pool)
	for {
		c.reconcileWarm(ctx, pool, log)
		if !sleepCtx(ctx, c.cfg.WarmInterval) {
			return
		}
	}
}

// reconcileWarm spawns enough workers to reach WarmIdle idle workers, counting
// pods that are still starting so back-to-back ticks do not over-spawn.
func (c *Controller) reconcileWarm(ctx context.Context, pool string, log *slog.Logger) {
	ctx, span := tracer.Start(ctx, "controller.warm_reconcile", trace.WithAttributes(attrPool.String(pool)))
	defer span.End()
	p, err := c.api.GetPoolForRepository(ctx, pool, c.cfg.Repository)
	if err != nil {
		if errors.Is(err, cursorapi.ErrNotFound) {
			p = &cursorapi.Pool{PoolName: pool}
		} else {
			log.Error("warm: get pool", "err", err)
			c.authCheck(err)
			return
		}
	}
	if err := c.syncWorkerClaims(ctx, log); err != nil {
		log.Warn("warm: sync worker claims", "err", err)
		c.authCheck(err)
	}
	starting := 0
	if workers, err := c.backend.ListWorkers(ctx); err == nil {
		for _, w := range workers {
			if w.Pool == pool && w.RequestID == "" && w.Live != nil && *w.Live && c.now().Sub(w.CreatedAt) < 5*time.Minute {
				starting++
			}
		}
	} else {
		log.Warn("warm: list workers", "err", err)
	}
	deficit := c.cfg.WarmIdle - p.IdleWorkerCount() - starting
	c.m.WarmDeficit.WithLabelValues(pool).Set(float64(deficit))
	span.SetAttributes(attribute.Int("cursor.warm_deficit", deficit), attribute.Int("cursor.idle_workers", p.IdleWorkerCount()))
	if deficit <= 0 {
		return
	}
	log.Info("warm: spawning idle workers", "deficit", deficit, "idle", p.IdleWorkerCount(), "starting", starting)
	for i := 0; i < deficit && ctx.Err() == nil; i++ {
		spec := backend.Spec{WorkerID: backend.NewWorkerID(c.cfg.WorkerIDPrefix), Pool: pool, Kind: backend.KindWarm, APIURL: c.cfg.APIURL}
		if err := c.backend.Spawn(ctx, spec); err != nil {
			c.m.Spawns.WithLabelValues(pool, string(backend.KindWarm), "error").Inc()
			log.Error("warm: spawn failed", "worker", spec.WorkerID, "err", err)
			return
		}
		c.m.Spawns.WithLabelValues(pool, string(backend.KindWarm), "ok").Inc()
	}
}

// syncWorkerClaims repairs durable warm-worker claim state after missed events
// or controller restarts.
func (c *Controller) syncWorkerClaims(ctx context.Context, log *slog.Logger) error {
	workers, err := c.api.ListAllWorkers(ctx, cursorapi.WorkerListOptions{Status: "all", Scope: "team_pool", Limit: 100})
	if err != nil {
		return err
	}
	for _, worker := range workers {
		if worker.ActiveBcID != "" {
			c.recordClaim(ctx, worker.WorkerID, worker.ActiveBcID, log)
		}
	}
	return nil
}

// ---------------------------------------------------------------------------
// garbage collection

func (c *Controller) gcLoop(ctx context.Context) {
	for {
		if !sleepCtx(ctx, c.cfg.GCInterval) {
			return
		}
		if err := c.RunGC(ctx); err != nil {
			c.m.GCErrors.Inc()
			c.log.Error("gc pass failed", "err", err)
		}
	}
}

// Disposal reasons.
const (
	ReasonTTL            = "ttl"
	ReasonAgentArchived  = "agent_archived"
	ReasonAgentDeleted   = "agent_deleted"
	ReasonUnclaimed      = "unclaimed"
	ReasonStartupTimeout = "startup_timeout"
)

// RunGC performs one disposal pass.
func (c *Controller) RunGC(ctx context.Context) error {
	ctx, span := tracer.Start(ctx, "controller.gc")
	defer span.End()
	c.m.GCRuns.Inc()
	workers, err := c.backend.ListWorkers(ctx)
	if err != nil {
		spanResult(span, "list_error", err)
		return err
	}
	var live, idle, unknown int
	for _, w := range workers {
		if !c.backend.Owns(w.ID) {
			continue
		}
		isLive, known := c.liveness(ctx, w)
		if !known {
			unknown++
			continue
		}
		if isLive {
			live++
			continue
		}
		idle++
		reason := c.disposeReason(ctx, w)
		if reason == "" {
			continue
		}
		log := c.log.With("worker", w.ID, "request", w.RequestID, "pool", w.Pool, "reason", reason, "idle", c.now().Sub(w.LastActivity).Round(time.Second))
		c.dispose(ctx, w, reason, log)
	}
	span.SetAttributes(attribute.Int("cursor.workers_live", live), attribute.Int("cursor.workers_idle", idle), attribute.Int("cursor.workers_unknown", unknown))
	c.m.Workers.WithLabelValues("live").Set(float64(live))
	c.m.Workers.WithLabelValues("idle").Set(float64(idle))
	c.m.Workers.WithLabelValues("unknown").Set(float64(unknown))
	return nil
}

func (c *Controller) dispose(ctx context.Context, w backend.WorkerInfo, reason string, log *slog.Logger) {
	ctx, span := tracer.Start(ctx, "controller.dispose",
		trace.WithAttributes(attrWorkerID.String(w.ID), attrRequestID.String(w.RequestID), attrPool.String(w.Pool), attrReason.String(reason)))
	defer span.End()
	if err := c.backend.Dispose(ctx, w.ID, reason); err != nil {
		c.m.Disposals.WithLabelValues(reason, "error").Inc()
		spanResult(span, "dispose_error", err)
		log.Error("dispose failed", "err", err)
		return
	}
	c.m.Disposals.WithLabelValues(reason, "ok").Inc()
	spanResult(span, "disposed", nil)
	log.Info("disposed worker")
	if reason == ReasonStartupTimeout && w.RequestID != "" {
		c.release(ctx, w.RequestID, ReasonStartupTimeout)
	}
}

// liveness uses the backend's view when it has one, else asks Cursor whether
// the worker is connected.
func (c *Controller) liveness(ctx context.Context, w backend.WorkerInfo) (live, known bool) {
	if w.Live != nil {
		return *w.Live, true
	}
	_, err := c.api.GetWorker(ctx, w.ID)
	switch {
	case err == nil:
		return true, true
	case errors.Is(err, cursorapi.ErrNotFound):
		return false, true
	default:
		c.log.Warn("gc: get worker", "worker", w.ID, "err", err)
		c.authCheck(err)
		return false, false
	}
}

// disposeReason decides whether an offline worker should be disposed now.
func (c *Controller) disposeReason(ctx context.Context, w backend.WorkerInfo) string {
	if w.StartupTimedOut {
		return ReasonStartupTimeout
	}
	last := w.LastActivity
	if last.IsZero() {
		last = w.CreatedAt
	}
	if last.IsZero() {
		return ""
	}
	idle := c.now().Sub(last)
	if c.cfg.DisposeAfter > 0 && idle >= c.cfg.DisposeAfter {
		return ReasonTTL
	}
	if w.RequestID == "" {
		if c.cfg.DisposeUnclaimedAfter > 0 && idle >= c.cfg.DisposeUnclaimedAfter {
			return ReasonUnclaimed
		}
		return ""
	}
	if !c.cfg.CheckAgent || c.agentChecksDisabled() || idle < c.cfg.DisposeArchivedAfter {
		return ""
	}
	agent, err := c.api.GetAgent(ctx, w.RequestID)
	switch {
	case errors.Is(err, cursorapi.ErrNotFound):
		return ReasonAgentDeleted
	case cursorapi.IsAuthError(err):
		c.disableAgentChecks(err)
		return ""
	case err != nil:
		c.log.Warn("gc: get agent", "agent", w.RequestID, "err", err)
		return ""
	}
	if agent.Status == cursorapi.AgentStatusArchived {
		return ReasonAgentArchived
	}
	return ""
}

func (c *Controller) agentChecksDisabled() bool {
	c.agentCheckMu.Lock()
	defer c.agentCheckMu.Unlock()
	return c.agentCheckDisabled
}

func (c *Controller) disableAgentChecks(err error) {
	c.agentCheckMu.Lock()
	defer c.agentCheckMu.Unlock()
	if !c.agentCheckDisabled {
		c.agentCheckDisabled = true
		c.log.Warn("gc: api key cannot read /v1/agents; archived-agent disposal disabled, TTL disposal still active", "err", err)
	}
}

func poolLabel(pool string) string {
	if pool == "" {
		return "*"
	}
	return pool
}

func truncate(s string, n int) string {
	if len(s) <= n {
		return s
	}
	return s[:n] + "..."
}
